// Auto-generated sidebar: every synced Markdown file appears without manual entries.
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
